# Generated by Django 3.1.7 on 2021-03-24 12:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.TextField(blank=True, null=True)),
                ('stock_name', models.TextField(blank=True, null=True)),
                ('stock_price', models.IntegerField(blank=True, null=True)),
                ('high_price', models.IntegerField(blank=True, null=True)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('end_price', models.IntegerField(blank=True, null=True)),
                ('sell_count', models.IntegerField(blank=True, null=True)),
                ('sell_price', models.IntegerField(blank=True, null=True)),
                ('updown', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portname', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 24, 12, 15, 46, 94696, tzinfo=utc))),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=200)),
                ('sector_per', models.IntegerField(blank=True, null=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='portfolio.myport')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 3, 24, 12, 15, 46, 92818, tzinfo=utc))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mycorp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.TextField(blank=True, null=True, unique=True)),
                ('stock_name', models.TextField(blank=True, null=True, unique=True)),
                ('stock_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 24, 12, 15, 46, 96158, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corps', to='portfolio.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolio.post')),
            ],
        ),
    ]
