# Generated by Django 3.1.7 on 2021-03-24 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210324_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 24, 12, 23, 10, 569255, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mycorp',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 24, 12, 23, 10, 571748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='myport',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 24, 12, 23, 10, 570262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='myport',
            name='portname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 24, 12, 23, 10, 568366, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
