# Generated by Django 3.1.7 on 2021-03-16 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210316_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='stock_code',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corp',
            name='stock_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 8, 19, 6, 313815, tzinfo=utc)),
        ),
    ]
