# Generated by Django 3.1.7 on 2021-03-16 08:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210316_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='stock_code',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 8, 22, 29, 127660, tzinfo=utc)),
        ),
    ]
