# Generated by Django 3.1.7 on 2021-03-23 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210319_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 11, 56, 29, 962400, tzinfo=utc)),
        ),
    ]
