# Generated by Django 3.1.7 on 2021-03-23 11:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0008_auto_20210323_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portname', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 23, 11, 57, 14, 114256, tzinfo=utc))),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 11, 57, 14, 112894, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=200)),
                ('sector_per', models.IntegerField(blank=True, null=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='portfolio.myport')),
            ],
        ),
        migrations.CreateModel(
            name='Mycorp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.TextField(blank=True, null=True, unique=True)),
                ('stock_name', models.TextField(blank=True, null=True, unique=True)),
                ('stock_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 23, 11, 57, 14, 115155, tzinfo=utc))),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corps', to='portfolio.sector')),
            ],
        ),
    ]
