# Generated by Django 3.1.7 on 2021-03-25 02:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210325_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 30, 20, 509750, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='corp',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 30, 20, 511787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mycorp',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 30, 20, 511224, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='myport',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 30, 20, 510287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 30, 20, 508955, tzinfo=utc)),
        ),
    ]
