# Generated by Django 3.1.7 on 2021-03-25 02:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20210325_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 32, 23, 934319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='corp',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mycorp',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 32, 23, 935812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='myport',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 32, 23, 934895, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 32, 23, 933377, tzinfo=utc)),
        ),
    ]
