# Generated by Django 3.1.7 on 2021-03-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20210325_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
