# Generated by Django 3.1.7 on 2021-03-25 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20210325_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
