# Generated by Django 3.1.7 on 2021-03-26 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0018_auto_20210325_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycorp',
            old_name='author',
            new_name='username',
        ),
        migrations.AddField(
            model_name='sector',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
