# Generated by Django 3.1.7 on 2021-03-26 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20210326_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycorp',
            name='port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corps', to='portfolio.myport'),
        ),
        migrations.AlterField(
            model_name='mycorp',
            name='stock_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mycorp',
            name='stock_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
