# Generated by Django 3.1.7 on 2021-03-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_mycorp_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycorp',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corps', to='portfolio.sector'),
        ),
    ]
