# Generated by Django 3.1.7 on 2021-03-30 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20210330_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='stock_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_price', to='portfolio.mycorp'),
        ),
    ]
