# Generated by Django 3.1.7 on 2021-03-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_auto_20210330_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='stock_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
