# Generated by Django 3.1.7 on 2021-03-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_auto_20210330_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='corp',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='portfolio.mycorp'),
        ),
    ]
