# Generated by Django 3.1.7 on 2021-03-30 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_corp_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='portfolio.mycorp'),
        ),
    ]
