# Generated by Django 3.1.7 on 2021-03-30 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_auto_20210330_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corp',
            name='info',
        ),
        migrations.AddField(
            model_name='mycorp',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='portfolio.corp'),
        ),
    ]
