# Generated by Django 3.1.7 on 2021-03-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_auto_20210330_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='myport',
            name='port_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
