# Generated by Django 3.1.7 on 2021-03-30 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_auto_20210330_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycorp',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='portfolio.corp'),
        ),
    ]
