# Generated by Django 3.1.7 on 2021-03-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_mycorp_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='sector_name',
            field=models.CharField(default='종목', max_length=200),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_per',
            field=models.IntegerField(default=0),
        ),
    ]
