# Generated by Django 3.1.7 on 2021-03-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_auto_20210331_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='sector_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
