# Generated by Django 3.1.7 on 2021-03-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_auto_20210331_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='sector_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
