# Generated by Django 3.1.7 on 2021-03-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0039_auto_20210331_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='sector_per',
            field=models.IntegerField(null=True),
        ),
    ]
