# Generated by Django 3.1.7 on 2021-03-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_auto_20210331_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='myport',
            name='cash_price',
            field=models.IntegerField(default=0),
        ),
    ]
