# Generated by Django 3.1.7 on 2021-04-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0041_myport_cash_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='myport',
            name='cash_per',
            field=models.IntegerField(default=0),
        ),
    ]
